assets:
  otc_list:
    - "EURUSD_otc"
    - "GBPUSD_otc"
    - "USDJPY_otc"
    - "AUDUSD_otc"
    - "USDCAD_otc"
    - "NZDUSD_otc"
    - "EURJPY_otc"
    - "EURGBP_otc"
    - "GBPJPY_otc"
    - "USDCHF_otc"
    - "AUDJPY_otc"
    - "AUDCAD_otc"
    - "EURAUD_otc"
    - "CADJPY_otc"
    - "EURCHF_otc"
    - "GBPCAD_otc"
    - "GBPAUD_otc"
    - "NZDJPY_otc"
    - "CHFJPY_otc"
    - "EURCAD_otc"
    - "AUDCHF_otc"
    - "CADCHF_otc"
    - "XAUUSD_otc"
    - "XAGUSD_otc"
    - "XPTUSD_otc"
    - "BTCUSD_otc"
    - "ETHUSD_otc"
    - "LTCUSD_otc"
    - "XRPUSD_otc"
    - "DOGEUSD_otc"
    - "BNBUSD_otc"
    - "SOLUSD_otc"
    - "ADAUSD_otc"
    - "TRXUSD_otc"
    - "DOTUSD_otc"
  categories:
    forex:
      - "EURUSD_otc"
      - "GBPUSD_otc"
      - "USDJPY_otc"
      - "AUDUSD_otc"
      - "USDCAD_otc"
      - "NZDUSD_otc"
      - "EURJPY_otc"
      - "EURGBP_otc"
      - "GBPJPY_otc"
      - "USDCHF_otc"
      - "AUDJPY_otc"
      - "AUDCAD_otc"
      - "EURAUD_otc"
      - "CADJPY_otc"
      - "EURCHF_otc"
      - "GBPCAD_otc"
      - "GBPAUD_otc"
      - "NZDJPY_otc"
      - "CHFJPY_otc"
      - "EURCAD_otc"
      - "AUDCHF_otc"
      - "CADCHF_otc"
    metals:
      - "XAUUSD_otc"
      - "XAGUSD_otc"
      - "XPTUSD_otc"
    crypto:
      - "BTCUSD_otc"
      - "ETHUSD_otc"
      - "LTCUSD_otc"
      - "XRPUSD_otc"
      - "DOGEUSD_otc"
      - "BNBUSD_otc"
      - "SOLUSD_otc"
      - "ADAUSD_otc"
      - "TRXUSD_otc"
      - "DOTUSD_otc"
